name: Link Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-http2 --verbose --no-progress "**/*.md" "**/*.html"
